server:
  port: 8081

person:
  age: 18
  name: 张三



---
#开发环境
spring:
  profiles: dev
server:
  port: 8081

---
#测试环境
spring:
  profiles: test
server:
  port: 8082

---
#生产环境
spring:
  profiles: pro
server:
  port: 8083